{% set name = "capella-console-client" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/capella-console-client-{{ version }}.tar.gz
  sha256: 932ce08b06e3c94257efddf949405b4fcc3b27e10a2c861823f4b142ae88207f

build:
  entry_points:
    - capella-console-wizard = capella_console_client.cli.wizard:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - httpx >=0.18.2,<0.19.0
    - python >=3.6,<4.0
    - python-dateutil >=2.8.2,<3.0.0
    - retrying >=1.3.3,<2.0.0
    - rich >=10.16.2,<11.0.0
    - typer >=0.4.0,<1.0.0
    - questionary >=1.10.0,<2.0.0
    - tabulate >=0.8.9,<1.0.0

test:
  imports:
    - capella_console_client
  commands:
    - pip check
    - capella-console-wizard --help
  requires:
    - pip

about:
  home: https://github.com/capellaspace/console-client
  summary: Python SDK for api.capellaspace.com (search, order, download)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - grmpflh27
    - jordan-heemskerk
